apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-minio-secret
  namespace: platform-minio
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: platform-minio-secret
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: platform-minio-username
    - secretKey: rootPassword
      remoteRef:
        key: platform-minio-password