existingSecret: platform-minio-secret
mode: standalone
replicas: 1

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

buckets:
  - name: mlflow

env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: public
  - name: MINIO_PROMETHEUS_JOB_ID
    value: minio

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
    includeNode: true
