service:
  port: 80
  name: http
  containerPortName: mlflow

backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgres-cluster-rw.platform-postgres.svc
    port: 5432
    database: mlflow

  existingDatabaseSecret:
    name: platform-postgres-mlflow-secret
    usernameKey: username
    passwordKey: password

artifactRoot:
  proxiedArtifactStorage: true
  s3:
    enabled: true
    bucket: mlflow
    existingSecret:
      name: platform-minio-secret
      keyOfAccessKeyId: rootUser
      keyOfSecretAccessKey: rootPassword

serviceMonitor:
  enabled: true
  useServicePort: true
  namespace: platform-mlflow
  interval: 30s
  telemetryPath: /metrics
  labels:
    release: prometheus
  timeout: 10s
  targetLabels: []
  metricRelabelings: []

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: "http://minio.platform-minio.svc.cluster.local:9000"

extraFlags:
  - serveArtifacts
