namespaceOverride: platform-postgres
cluster:
  instances: 2
  # Backs the provisioned cloud-native-pg Grafana dashboard.
  monitoring:
    enabled: true
  storage:
    size: 1Gi
  roles:
    - name: postgres-mlflow
      login: true
      passwordSecret:
        name: platform-postgres-mlflow-secret
    - name: postgres-lakefs
      login: true
      passwordSecret:
        name: platform-postgres-lakefs-secret
