yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers:  platform-kafka-kafka-brokers.platform-kafka.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false