# 1) Kafka (KRaft) resource
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: platform-kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: 4.1.0
    config:
      inter.broker.protocol.version: "4.1"
      log.message.format.version: "4.1"
  entityOperator:
    topicOperator: {}
    userOperator: {}
---

# 2) Controller node pool
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: platform-kafka-controllers
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  replicas: 3
  roles: [controller]
  storage:
    type: persistent-claim
    size: 2Gi
    class: standard
---

# 3) Broker node pool
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: platform-kafka-brokers
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  replicas: 3
  roles: [broker]
  storage:
    type: persistent-claim
    size: 10Gi
    class: standard
