apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads-team2-postgres
resources:
  - ../../../../../../../bases/postgres
patchesStrategicMerge:
  - secret-patch.yaml
commonLabels:
  app.kubernetes.io/instance: team2
