prometheus:
  prometheusSpec:
    replicas: 1
    retention: 12h
    resources:
      requests: { cpu: 100m, memory: 256Mi }
      limits:   { cpu: 500m, memory: 512Mi }
    # allow Probes from all namespaces (not only those with Helm-set labels)
    probeSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false


alertmanager:
  alertmanagerSpec:
    replicas: 1

grafana:
  admin:
    existingSecret: platform-grafana-secret
    userKey: username
    passwordKey: password
  service:
    type: ClusterIP
  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }

# Trim non-essential control-plane targets for tiny clusters
kubeControllerManager: { enabled: false }
kubeScheduler:         { enabled: false }
coreDns:               { enabled: false }
kubeEtcd:              { enabled: false }

# Light exporter footprints
nodeExporter:
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits:   { cpu: 200m, memory: 128Mi }

kubeStateMetrics:
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits:   { cpu: 200m, memory: 128Mi }
