apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-team1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/michi2402/mlops-apps
    targetRevision: master
    path: clusters/local/k8s-native-stack/workloads/team1/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
