apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: "https://kv-mlops-eso.vault.azure.net"
      authType: ServicePrincipal
      tenantId: "c9e60896-3e78-4b46-8eff-cdb949495f6a"
      authSecretRef:
        clientId:
          name: azure-sp-secret
          key: ClientID
        clientSecret:
          name: azure-sp-secret
          key: ClientSecret