apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: "https://kv-mlops-eso.vault.azure.net"
      authType: ServicePrincipal
      tenantId:
        valueFrom:
          secretKeyRef:
            name: azure-sp-secret
            key: TenantID
      authSecretRef:
        clientId:
          name: azure-sp-secret
          key: ClientID
        clientSecret:
          name: azure-sp-secret
          key: ClientSecret