apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      vaultUrl: "https://kv-mlops-eso.vault.azure.net"
      tenantId: "c9e60896-3e78-4b46-8eff-cdb949495f6a"
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: azure-sp-secret
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: azure-sp-secret
          namespace: external-secrets
          key: ClientSecret