apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-team1-iris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: team1-iris
  source:
    repoURL: https://github.com/michi2402/mlops-apps
    path: base/charts/model
    targetRevision: master
    helm:
      valuesObject:
        nameOverride: "iris"
        minio:
          modelUri: "s3://mlflow/2/models/m-e5ef5b59c108428cbc459346f5c6d781/artifacts"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
