apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-minio-secret
  namespace: platform-mlflow
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: platform-minio-secret
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          serving.kserve.io/s3-endpoint: "minio.platform-minio.svc.cluster.local:9000"
          serving.kserve.io/s3-usehttps: "0"
          serving.kserve.io/s3-region: "us-east-1"
          serving.kserve.io/s3-usevirtualbucket: "false"
  data:
    - secretKey: rootUser
      remoteRef:
        key: platform-minio-username
    - secretKey: rootPassword
      remoteRef:
        key: platform-minio-password