apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crd-cnpg
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://github.com/cloudnative-pg/charts
    targetRevision: cloudnative-pg-v0.26.0
    path: charts/cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
