apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crd-eso
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://github.com/external-secrets/external-secrets
    targetRevision: v0.19.2
    path: deploy/charts/external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
