apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cloudnative-pg
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg
    targetRevision: release-1.27
    path: releases
    directory:
      include: cnpg-1.27.0.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
