apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crd-kserve
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  sources:
  - repoURL: ghcr.io/kserve/charts
    chart: kserve-crd
    targetRevision: v0.15.0

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
