apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cloudnative-pg
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-crds
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.26.0
    helm:
      releaseName: platform-cloudnative-pg
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
