apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-minio
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  sources:
    - repoURL: https://github.com/minio/minio
      targetRevision: RELEASE.2025-09-07T16-13-09Z
      path: helm/minio
      helm:
        releaseName: minio
        valueFiles:
          - $values/clusters/local/k8s-native-stack/platform/components/minio/values.yaml

    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
