apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-postgres
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  sources:
    - repoURL: https://github.com/cloudnative-pg/charts
      targetRevision: cluster-v0.3.1
      path: charts/cluster
      helm:
        releaseName: postgres
        valueFiles:
          - $values/clusters/local/k8s-native-stack/platform/components/postgres/values.yaml

    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
