apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
    - repoURL: https://github.com/external-secrets/external-secrets
      targetRevision: v0.19.2
      path: deploy/crds
      directory:
        include: bundle.yaml

    - repoURL: https://github.com/external-secrets/external-secrets
      targetRevision: v0.19.2
      path: deploy/charts/external-secrets
      helm:
        valuesObject:
          installCRDs: true

    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      path: base/external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
