apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-katib
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kubeflow
  source:
    repoURL: https://github.com/kubeflow/katib.git
    targetRevision: v0.17.0    
    path: manifests/v1beta1/installs/katib-cert-manager
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true