apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kfp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kubeflow
  source:
    repoURL: https://github.com/kubeflow/pipelines.git
    targetRevision: 2.14.0
    path: manifests/kustomize/env/platform-agnostic
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true