apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kubeflow-trainer-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kubeflow-system
  source:
    repoURL: https://github.com/kubeflow/trainer.git
    targetRevision: v2.0.0
    path: manifests/overlays/manager
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true