apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kubeflow-spark-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kubeflow-spark-operator
  sources:
  - repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 2.3.0
    helm:
      releaseName: spark-operator
      valueFiles:
        - $values/clusters/local/k8s-native-stack/platform/components/kubeflow-spark-operator/values.yaml

  - repoURL: https://github.com/michi2402/mlops-apps
    targetRevision: master
    path: clusters/local/k8s-native-stack/platform/components/kubeflow-spark-operator
    ref: values
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true