apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-rbac-pipeline-runner
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/michi2402/mlops-apps
    targetRevision: master
    path: clusters/local/k8s-native-stack/platform/components/rbac-pipeline-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true