apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-lakefs-secret
  namespace: platform-lakefs
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: platform-lakefs-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        databaseConnectionString: >-
          postgres://{{ .username }}:{{ .password }}@postgres-cluster-rw.platform-postgres.svc.cluster.local:5432/lakefs?sslmode=disable
        authEncryptSecretKey: "{{ .auth_key }}"
  data:
    - secretKey: username
      remoteRef:
        key: platform-postgres-lakefs-username
    - secretKey: password
      remoteRef:
        key: platform-postgres-lakefs-password
    - secretKey: auth_key
      remoteRef:
        key: platform-lakefs-auth-key