apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-team2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michi2402/mlops-apps
    targetRevision: master
    path: clusters/local/_skeleton/workloads/team2/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
