namespaceOverride: platform
cluster:
  instances: 2
  storage:
    size: 1Gi
  initdb:
    database: mlflow
    owner: mlflow
    postInitApplicationSQL:
    - CREATE USER lakefs WITH PASSWORD 'lakefspassword';