namespaceOverride: platform
cluster:
  instances: 2
  storage:
    size: 1Gi
  initdb:
    database: mlflow
    owner: mlflow
    users:
      - name: lakefs
        password: lakefspassword
        options: "CREATEDB"
    postInitApplicationSQL:
      - CREATE DATABASE lakefs OWNER lakefs;