existingSecret: platform-minio-secret
mode: standalone
replicas: 1
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
buckets:
  - name: mlflow
  - name: lakefs