apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-mlflow
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  sources:
    - repoURL: https://github.com/community-charts/helm-charts
      targetRevision: mlflow-1.6.2
      path: charts/mlflow
      helm:
        releaseName: mlflow
        valueFiles:
          - $values/clusters/local/_skeleton/platform/components/mlflow/values.yaml

    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
