apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-minio
  sources:
    - repoURL: https://github.com/minio/minio
      targetRevision: master         # or a tag/commit, e.g. "RELEASE.2025-08-24T03-56-07Z" when available
      path: helm/minio
      helm:
        releaseName: minio
        valueFiles:
          - $values/clusters/local/_skeleton/platform/components/minio/values.yaml

    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
