apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-envoy-gateway
  sources:
  - repoURL: oci://docker.io/envoyproxy/gateway-helm
    chart: gateway-helm
    targetRevision: v1.15.1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
