apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-envoy-gateway
  source:
    repoURL: docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: v1.5.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
