apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-envoy-gateway
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.5.1
    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      path: clusters/local/_skeleton/platform/components/envoy-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
