# argocd/app-strimzi.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: 0.48.0
      helm:
        values: |
        watchAnyNamespace: true

    - repoURL: https://github.com/michi2402/mlops-apps
      targetRevision: master
      path: clusters/local/_skeleton/platform/components/kafka
    
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kafka
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
