apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kserve
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kserve
  sources:
  - repoURL: ghcr.io/kserve/charts
    chart: kserve-crd
    targetRevision: v0.15.0

  - repoURL: ghcr.io/kserve/charts
    chart: kserve
    targetRevision: v0.15.0
    helm:
      releaseName: kserve
      valueFiles:
        - $values/clusters/local/_skeleton/platform/components/kserve/values.yaml

  - repoURL: https://github.com/michi2402/mlops-apps
    targetRevision: master
    path: clusters/local/_skeleton/platform/components/kserve
    ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
