# argocd/app-strimzi.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kafka-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: 0.48.0
      helm:
        values: |
        watchAnyNamespace: true
    
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
