apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-team1-iris
  namespace: team1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads-team1
  destination:
    server: https://kubernetes.default.svc
    namespace: team1-iris
  source:
    repoURL: https://github.com/michi2402/mlops-apps
    path: base/charts/model
    targetRevision: master
    helm:
      valuesObject:
        fullnameOverride: "iris"
        minio:
          modelUri: "s3://mlflow/1/models/m-12701b8c11df4471a2d6855bcd100003/artifacts"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
