apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-creds
  namespace: platform-kubeflow
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: ghcr-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{- $u := .username | toString -}}
          {{- $p := .token | toString -}}
          {{- $auth := printf "%s:%s" $u $p | b64enc -}}
          { "auths": { "ghcr.io": { "username": "{{ $u }}", "password": "{{ $p }}", "auth": "{{ $auth }}" } } }
  data:
    - secretKey: username
      remoteRef:
        key: platform-compute-ghcr-username
    - secretKey: token
      remoteRef:
        key: platform-compute-ghcr-password