apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ include "model.fullname" . }}
  annotations:
    serving.kserve.io/enable-prometheus-scraping: "true"
    prometheus.kserve.io/port: "8080"
    prometheus.kserve.io/path: "/metrics"
  labels: {{- include "model.labels" . | nindent 4 }}
spec:
  predictor:
    serviceAccountName: kserve-minio-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: {{ .Values.minio.modelUri | quote }}