apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ include "model.fullname" . }}
  labels: {{- include "model.labels" . | nindent 4 }}
spec:
  predictor:
    serviceAccountName: kserve-minio-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: {{ include ".Values.minio.modelUri" . }}