# svc: expose the metrics port on the predictor
apiVersion: v1
kind: Service
metadata:
  name: {{ include "model.fullname" . }}
  labels: {{- include "model.labels" . | nindent 4 }}
spec:
  selector:
    serving.kserve.io/inferenceservice: {{ include "model.fullname" . }}
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080

---
# ServiceMonitor: tell Prometheus what/where to scrape
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "model.fullname" . }}
  labels: {{- include "model.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      model.kserve.io/name: {{ include "model.fullname" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
