apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-team2
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: root
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true

spec:
  project: default
  source:
    repoURL: https://github.com/michi2402/mlops-apps
    targetRevision: master
    path: clusters/local/skeleton/workloads/team2/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
