apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../bases/platform/postgres
  - argocd-project.yaml
patches:
  - target:
      kind: Application
      name: postgres
    patch: |-
      - op: replace
        path: /spec/project
        value: local-example
