apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: platform
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 14.3.3
    helm:
      releaseName: postgres
      values: |
        primary:
          persistence:
            enabled: false
        auth:
          postgresPassword: postgres
          username: app
          password: app
          database: app
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
